# Generated by Django 3.1.7 on 2021-03-09 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='ticks/')),
                ('values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metronome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('frequency', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('bpm', models.PositiveIntegerField()),
                ('stereo', models.BooleanField(default=False)),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metronome.tick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
