# Generated by Django 3.1.7 on 2021-03-13 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metronome', '0002_auto_20210309_2333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metronome',
            unique_together={('user', 'title')},
        ),
    ]
