# Generated by Django 3.1.7 on 2021-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0003_auto_20210313_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metronome',
            name='frequency',
            field=models.CharField(choices=[('8000', 8000), ('11025', 11025), ('12000', 12000), ('16000', 16000), ('22050', 22050), ('24000', 24000), ('32000', 32000), ('44100', 44100), ('48000', 48000)], max_length=5),
        ),
    ]
