# Generated by Django 3.1.7 on 2021-03-14 00:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metronome', '0004_auto_20210313_1801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metronome',
            unique_together={('user', 'title'), ('user', 'frequency', 'duration', 'bpm', 'tick', 'stereo')},
        ),
    ]
