# Generated by Django 3.1.7 on 2021-03-14 14:17

from django.db import migrations
import metronome.models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0005_auto_20210314_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metronome',
            name='bpm',
            field=metronome.models.PositiveIntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='metronome',
            name='duration',
            field=metronome.models.PositiveIntegerRangeField(),
        ),
    ]
