# Generated by Django 3.1.7 on 2021-03-20 07:34

from django.db import migrations, models
import django.db.models.deletion
import metronome.models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0002_auto_20210320_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bpm',
            field=metronome.models.PositiveIntegerRangeField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='synchronizer.project'),
        ),
    ]
