# Generated by Django 3.1.7 on 2021-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0003_auto_20210320_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='instrument',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recording',
            name='samples',
            field=models.TextField(blank=True),
        ),
    ]
