# Generated by Django 3.1.7 on 2021-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0005_auto_20210321_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='first_beat_index',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to='InstrumentSynchronizerSite/static/recordings'),
        ),
    ]
